### ISSUE TITLE
some asp.net test pages do not work from installation

### ISSUE THREAD

**Issue by Longfld** [tpokorra/lbs-mono#11]
I have installed by follow yours step by step

but install : yum install mono-opt mono-xsp mod_mono-opt
instead of all as yum install mono-opt mono-xsp-opt mod_mono-opt mono-basic-opt mono-nant-opt nuget-opt

Because I only need for ASP.NET

Then I run
#. /opt/mono/env.sh
#cd /opt/mono/lib/xsp/test
#xsp4
xsp4
Listening on address: 0.0.0.0
Root directory: /opt/mono/lib/xsp/test
Listening on port: 9000 (non-secure)
Hit Return to stop the server.
Application_Start

Then I browser by http://localhost:900   and found many pages under localhost:9000/2.0/ does not working,
 e.g.
 http://localhost:9000/2.0/gridview/BasicGrid.aspx
 http://localhost:9000/2.0/gridview/ObjectBoundGrid.aspx
 http://localhost:9000/2.0/gridview/BasicGrid.aspx
 
 and I remember in previously it works.

And love and thanks for your work
Nan

**Comment by tpokorra** [comment]
Which OS are you using?

What is the link of my howto that you followed?

You say you installed mono-xsp? Please try installing mono-xsp-opt instead!

I have tried this on a clean CentOS7 machine:

```
yum install epel-release
cd /etc/yum.repos.d
wget https://copr.fedorainfracloud.org/coprs/tpokorra/mono-opt/repo/epel-7/tpokorra-mono-opt-epel-7.repo
yum install mono-opt mono-xsp-opt
. /opt/mono/env.sh
cd /opt/mono/lib/xsp/test
xsp4
```

Then went to http://localhost:9000/2.0/gridview/BasicGrid.aspx

The error I got was:

```
System.DllNotFoundException
libgdiplus.so.0

Description: HTTP 500.Error processing request.

Details: Non-web exception.
Exception stack trace:
  at (wrapper managed-to-native) System.Drawing.GDIPlus:GdiplusStartup (ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)
  at System.Drawing.GDIPlus..cctor () [0x000cc] in <1917aa1c39d94b1a91807b8cd9f03350>:0 
```

So this should solve it:

```
yum install mono-libgdiplus-opt
```

Now it seems to work.

hope this helps!

**Comment by Longfld** [comment]
Thanks for your help tpokorra,

After I install mono-libgdiplus-opt, it works.
As I only use mono to host asp.net web site, I had installed "#yum install mono-opt mono-xsp-opt mod_mono-opt".
It looks needs mono-libgdiplus-opt as well.
Thanks again for help.
