### ISSUE TITLE
CentOS5 mono-opt make fails

### ISSUE THREAD

**Issue by tpokorra** [tpokorra/lbs-mono#8]
```
/usr/bin/ld: ./.libs/libmini.a(libmini_la-mini.o): relocation R_X86_64_PC32 against `mono_cross_helpers_run' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
```

**Comment by tpokorra** [comment]
see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=194652
though it should not be in a freebsd bug tracker???

**Comment by tpokorra** [comment]
disabling shared libraries:

`./configure --prefix=%{MonoPath} --enable-llvm --with-llvm=%{MonoPath} --with-shared_mono=no`

this causes:

```
make[3]: Entering directory `/usr/src/redhat/BUILD/mono-3.12.1/mono/dis'
  CC       get.o
  CC       dis-cil.o
  CC       util.o
  AR       libmonodis.a
  CC       dump.o
  CC       main.o
  CC       declsec.o
make[3]: *** No rule to make target `../mini/libmonosgen-2.0.la', needed by `monodis'.  Stop.
make[3]: Leaving directory `/usr/src/redhat/BUILD/mono-3.12.1/mono/dis'
```

**Comment by tpokorra** [comment]
need a newer gcc version. see http://ask.xmodulo.com/upgrade-gcc-centos.html

**Comment by tpokorra** [comment]
works now for 32 bit.
on 64 bit: http://stackoverflow.com/questions/16927885/usr-bin-ld-skipping-incompatible-foo-so-when-searching-for-foo

**Comment by tpokorra** [comment]
builds now

**Comment by fabricioncosta** [comment]
tpokorra, I am facing the same problem. Could you explain better what should I do to compile in 32 bits. Call the configure with "build=i686-pc-linux-gnu" wont work for me...Thanks

**Comment by tpokorra** [comment]
fabricioncosta, I am using a newer version of GCC by using the repo http://people.centos.org/tru/devtools-2/devtools-2.repo

I also use the epel repo.

I need to install these packages:

```
  yum -y install gcc libtool bison gettext make bzip2 automake gcc-c++ patch dos2unix mono-llvm-opt mono-llvm-opt-devel devtoolset-2 libgdiplus
```

Important: devtoolset-2
